name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t stryukovvlad/lab2_otrpo:latest .

      - name: Push Docker image
        run: |
          docker push stryukovvlad/lab2_otrpo:latest
